// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqmubdlnqulofclhovwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbXViZGxucXVsb2ZjbGhvdndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjA0MzQsImV4cCI6MjA2NjU5NjQzNH0.k9bjMrwnXyNiMGI5zlkbRUR4PmGgyVDQkQh92r_9yBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);